Repository coconut-svsm/svsm, pull requests merged in 2024-06, with the labels that each got.

#358 Add a separate crate insn_decode in kernel for instruction decoding
  fuzz/fuzz_targets/insn.rs
  kernel/src/cpu/control_regs.rs
  kernel/src/cpu/gdt.rs
  kernel/src/cpu/idt/common.rs
  kernel/src/cpu/insn.rs
  kernel/src/cpu/mod.rs
  kernel/src/cpu/registers.rs
  kernel/src/cpu/vc.rs
  kernel/src/error.rs
  kernel/src/insn_decode/decode.rs
  kernel/src/insn_decode/insn.rs
  kernel/src/insn_decode/mod.rs
  kernel/src/insn_decode/opcode.rs
  kernel/src/lib.rs
  kernel/src/sev/ghcb.rs
  kernel/src/types.rs
Labels: ready-to-merge

#363 task/schedule: fix module-level documentation
  kernel/src/task/schedule.rs
Labels: documentation, ready-to-merge

#339 OpenSSF Badge Score
  README.md
Labels: wait-for-update

#371 docs: add owner of ApicEmul item
  Documentation/docs/developer/DEVELOPMENT-PLAN.md
Labels: wait-for-update

#356 igvm: initial support for TD Partitioning
  Makefile
  bootlib/src/igvm_params.rs
  bootlib/src/platform.rs
  igvmbuilder/src/cmd_options.rs
  igvmbuilder/src/gpa_map.rs
  igvmbuilder/src/igvm_builder.rs
  igvmbuilder/src/ovmf_firmware.rs
  igvmbuilder/src/stage2_stack.rs
  kernel/src/error.rs
  kernel/src/platform/mod.rs
  kernel/src/platform/tdp.rs
  stage1/stage1.S
Labels: needs-rebase

#386 cpu/apic: Clean up APIC emulation code
  igvmbuilder/src/igvm_builder.rs
  kernel/src/cpu/apic.rs
  kernel/src/cpu/percpu.rs
  kernel/src/protocols/apic.rs
Labels: wait-for-review, needs-rebase
