Repository coconut-svsm/svsm, pull requests merged in 2024-10, with the labels that each got.

#451 soundness improvements around hypervisor-shared memory
  Cargo.lock
  kernel/Cargo.toml
  kernel/src/cpu/percpu.rs
  kernel/src/greq/driver.rs
  kernel/src/greq/msg.rs
  kernel/src/mm/page_visibility.rs
  kernel/src/sev/ghcb.rs
  kernel/src/sev/hv_doorbell.rs
  kernel/src/stage2.rs
Labels: in-review

#466 some fixes for the #HV handler
  kernel/src/cpu/idt/entry.S
  kernel/src/cpu/percpu.rs
Labels: in-review

#472 igmvbuilder: support VSM isolation platform type
  Makefile
  igvmbuilder/src/cmd_options.rs
  igvmbuilder/src/igvm_builder.rs
  igvmbuilder/src/stage2_stack.rs
  igvmbuilder/src/vmsa.rs
Labels: wait-for-review

#473 Enabling SMEP and SMAP
  kernel/Cargo.toml
  kernel/src/cpu/control_regs.rs
  kernel/src/cpu/features.rs
  kernel/src/cpu/idt/common.rs
  kernel/src/cpu/idt/entry.S
  kernel/src/cpu/idt/svsm.rs
  kernel/src/cpu/mod.rs
  kernel/src/cpu/x86/mod.rs
  kernel/src/cpu/x86/smap.S
  kernel/src/cpu/x86/smap.rs
Labels: in-review

#480 cpuarch/vmsa: fix soundness issue with GuestVMExit
  cpuarch/src/vmsa.rs
Labels: needs-rebase

#494 platform: move AP #HV doorbell initialization to platform
  kernel/src/cpu/smp.rs
  kernel/src/platform/snp.rs
Labels: in-review

#410 SSE and FPU support
  kernel/src/cpu/control_regs.rs
  kernel/src/cpu/mod.rs
  kernel/src/cpu/smp.rs
  kernel/src/cpu/sse.rs
  kernel/src/cpu/vc.rs
  kernel/src/mm/address_space.rs
  kernel/src/svsm.rs
  kernel/src/task/schedule.rs
  kernel/src/task/tasks.rs
Labels: wait-for-update

#460 get rid of unnecessary uses of unsafe
  kernel/src/acpi/tables.rs
  kernel/src/fw_cfg.rs
  kernel/src/fw_meta.rs
  kernel/src/greq/pld_report.rs
  kernel/src/greq/services.rs
  kernel/src/mm/pagebox.rs
  kernel/src/string.rs
Labels: in-review
