Repository coconut-svsm/svsm, pull requests merged in 2024-12, with the labels that each got.

#517 stage1: Rustify stage1 and update IGVM VTOM on TDP platforms
  .github/workflows/rust.yml
  Cargo.lock
  Cargo.toml
  Makefile
  bootlib/src/kernel_launch.rs
  igvmbuilder/src/gpa_map.rs
  igvmbuilder/src/stage2_stack.rs
  kernel/Cargo.toml
  kernel/src/platform/tdp.rs
  kernel/src/stage2.rs
  scripts/build.py
  stage1/Cargo.toml
  stage1/build.rs
  stage1/src/reset.S
  stage1/src/stage1.rs
  stage1/stage1.S
  stage1/stage1.lds
  stage1/types.h
  utils/gen_meta.c
Labels: in-review

#546 Making zero_mem_region() and control regs helpers unsafe
  kernel/src/cpu/control_regs.rs
  kernel/src/mm/alloc.rs
  kernel/src/platform/snp_fw.rs
  kernel/src/protocols/core.rs
  kernel/src/svsm.rs
  kernel/src/utils/util.rs
Labels: needs-rebase, in-review

#553 kernel/cpu: add safety comments
  kernel/src/cpu/control_regs.rs
  kernel/src/cpu/cpuid.rs
  kernel/src/cpu/idt/common.rs
  kernel/src/cpu/irq_state.rs
  kernel/src/cpu/mem.rs
  kernel/src/cpu/msr.rs
  kernel/src/cpu/shadow_stack.rs
  kernel/src/cpu/sse.rs
  kernel/src/cpu/tlb.rs
Labels: in-review

#555 cpu: use temporary GDT structures to load TSS
  kernel/src/cpu/gdt.rs
  kernel/src/cpu/idt/common.rs
  kernel/src/cpu/mod.rs
  kernel/src/cpu/percpu.rs
  kernel/src/cpu/vmsa.rs
  kernel/src/stage2.rs
  kernel/src/svsm.rs
Labels: in-review

#548 File System SysCalls
  Cargo.lock
  fuzz/fuzz_targets/fs.rs
  kernel/src/cpu/idt/svsm.rs
  kernel/src/error.rs
  kernel/src/fs/api.rs
  kernel/src/fs/buffer.rs
  kernel/src/fs/filesystem.rs
  kernel/src/fs/mod.rs
  kernel/src/fs/obj.rs
  kernel/src/fs/ramfs.rs
  kernel/src/mm/alloc.rs
  kernel/src/mm/guestmem.rs
  kernel/src/mm/mod.rs
  kernel/src/mm/vm/mapping/file_mapping.rs
  kernel/src/syscall/class1.rs
  kernel/src/task/exec.rs
  syscall/Cargo.toml
  syscall/src/call.rs
  syscall/src/class1.rs
  syscall/src/def.rs
Labels: in-review

#562 string: Deprecate FixedString
  kernel/src/acpi/tables.rs
  kernel/src/fs/api.rs
  kernel/src/fs/filesystem.rs
  kernel/src/fs/obj.rs
  kernel/src/fs/ramfs.rs
  kernel/src/fw_cfg.rs
  kernel/src/lib.rs
  kernel/src/string.rs
  kernel/src/syscall/class1.rs
  syscall/src/def.rs
Labels: in-review

#567 build: include FW file in hyper-v configuration
  configs/hyperv-target.json
Labels: in-review

#572 svsm_paging: Ensure page alignment during invalidation
  kernel/src/svsm_paging.rs
Labels: ready-to-merge

#568 kernel: use TPR for interrupt reentrancy protection
  kernel/src/cpu/idt/svsm.rs
  kernel/src/cpu/irq_state.rs
  kernel/src/cpu/mod.rs
  kernel/src/cpu/percpu.rs
  kernel/src/locking/common.rs
  kernel/src/locking/mod.rs
  kernel/src/locking/rwlock.rs
  kernel/src/locking/spinlock.rs
  kernel/src/sev/hv_doorbell.rs
  kernel/src/task/schedule.rs
  kernel/src/types.rs
Labels: in-review

#576 libtcgtpm: update _plat__NVEnable and _plat__NVDisable signatures
  kernel/src/vtpm/tcgtpm/mod.rs
  libtcgtpm/deps/libtcgtpm.h
Labels: in-review

#575 testing: support configurations other than SNP/QEMU
  Makefile
  bootlib/src/igvm_params.rs
  igvmbuilder/src/igvm_builder.rs
  kernel/src/config.rs
  kernel/src/cpu/vc.rs
  kernel/src/greq/services.rs
  kernel/src/igvm_params.rs
  kernel/src/lib.rs
  kernel/src/platform/mod.rs
  kernel/src/platform/native.rs
  kernel/src/platform/snp.rs
  kernel/src/platform/tdp.rs
  kernel/src/svsm.rs
  kernel/src/testing.rs
  kernel/src/testutils.rs
Labels: in-review
