Repository coconut-svsm/svsm, pull requests merged in 2024-03, with the labels that each got.

#278 Enable the use of VTOM in the SVSM
  bootlib/src/kernel_launch.rs
  igvmbuilder/src/igvm_builder.rs
  igvmbuilder/src/vmsa.rs
  kernel/src/boot_stage2.rs
  kernel/src/config.rs
  kernel/src/cpu/smp.rs
  kernel/src/cpu/vmsa.rs
  kernel/src/igvm_params.rs
  kernel/src/mm/pagetable.rs
  kernel/src/sev/status.rs
  kernel/src/stage2.rs
  kernel/src/svsm.rs
Labels: ready-to-merge

#274 acpi: Allow firmware path configuration
  Documentation/INSTALL.md
  kernel/src/acpi/tables.rs
Labels: ready-to-merge

#280 scripts/check-signed-off: use `--no-merges` when listing commits
  scripts/check-signed-off.sh
Labels: Merged

#281 igvmbuilder/stage2_stack: compile-time check stage 2 stack & remove needless allocation
  igvmbuilder/src/igvm_builder.rs
  igvmbuilder/src/stage2_stack.rs
Labels: Merged

#293 Prevent use of ImmutAfterInit in the multithreaded environment
  kernel/src/console.rs
  kernel/src/cpu/smp.rs
  kernel/src/mm/pagetable.rs
  kernel/src/utils/immut_after_init.rs
Labels: wait-for-review, ready-to-merge

#300 cpu/vc: improve error handling
  kernel/src/cpu/idt/stage2.rs
  kernel/src/cpu/idt/svsm.rs
  kernel/src/cpu/vc.rs
Labels: wait-for-review

#288 sev/ghcb Add #VC handler tests
  kernel/src/cpu/msr.rs
  kernel/src/cpu/vc.rs
  kernel/src/sev/utils.rs
  scripts/launch_guest.sh
Labels: wait-for-update

#298 Documentation: update QEMU v8.2.0 parameters and fix launch_guest.sh example
  Documentation/INSTALL.md
Labels: in-review

#294 Ensure IGVM output is compatible with QEMU and calculate launch measurement
  .github/workflows/rust.yml
  Cargo.lock
  Cargo.toml
  Makefile
  igvmbuilder/src/gpa_map.rs
  igvmbuilder/src/igvm_builder.rs
  igvmbuilder/src/vmsa.rs
  igvmmeasure/.cargo/config.toml
  igvmmeasure/Cargo.toml
  igvmmeasure/README.md
  igvmmeasure/src/cmd_options.rs
  igvmmeasure/src/igvm_measure.rs
  igvmmeasure/src/main.rs
  igvmmeasure/src/page_info.rs
Labels: in-review
