Repository coconut-svsm/svsm, pull requests merged in 2024-11, with the labels that each got.

#455 implement shadow stacks
  kernel/Cargo.toml
  kernel/src/address.rs
  kernel/src/cpu/extable.rs
  kernel/src/cpu/idt/common.rs
  kernel/src/cpu/idt/entry.S
  kernel/src/cpu/idt/svsm.rs
  kernel/src/cpu/isst.rs
  kernel/src/cpu/mod.rs
  kernel/src/cpu/percpu.rs
  kernel/src/cpu/shadow_stack.rs
  kernel/src/cpu/vc.rs
  kernel/src/cpu/vmsa.rs
  kernel/src/mm/address_space.rs
  kernel/src/mm/pagetable.rs
  kernel/src/mm/vm/mapping/mod.rs
  kernel/src/mm/vm/mapping/shadow_stack.rs
  kernel/src/mm/vm/mapping/vmalloc.rs
  kernel/src/mm/vm/mod.rs
  kernel/src/svsm.rs
  kernel/src/task/schedule.rs
  kernel/src/task/tasks.rs
Labels: in-review

#486 Setup verification
  .cargo/config.toml
  Cargo.lock
  Cargo.toml
  Documentation/docs/developer/VERIFICATION.md
  kernel/Cargo.toml
  kernel/build.rs
  kernel/src/address.rs
  kernel/src/address.verus.rs
  kernel/src/address_inner.verus.rs
  kernel/src/types.rs
  kernel/src/types.verus.rs
  scripts/vfmt.sh
  scripts/vinstall.sh
  verify_external/Cargo.toml
  verify_external/build.rs
  verify_external/src/convert.rs
  verify_external/src/convert.verus.rs
  verify_external/src/lib.rs
  verify_proof/Cargo.toml
  verify_proof/build.rs
  verify_proof/src/bits.rs
  verify_proof/src/bits.verus.rs
  verify_proof/src/lib.rs
Labels: in-review

#516 Userspace support: Implement opendir and readdir syscalls
  kernel/src/cpu/idt/svsm.rs
  kernel/src/fs/api.rs
  kernel/src/fs/filesystem.rs
  kernel/src/fs/mod.rs
  kernel/src/fs/obj.rs
  kernel/src/string.rs
  kernel/src/syscall/class1.rs
  kernel/src/syscall/mod.rs
  kernel/src/syscall/obj.rs
  syscall/src/class1.rs
  syscall/src/def.rs
  syscall/src/lib.rs
  syscall/src/obj.rs
Labels: wait-for-review

#524 kernel/tdx: Fix TDX error codes
  kernel/src/mm/pagetable.rs
  kernel/src/tdx/error.rs
  kernel/src/tdx/tdcall.rs
Labels: ready-to-merge

#526 kernel: remove unnecessary `unsafe`
  kernel/src/cpu/gdt.rs
  kernel/src/cpu/irq_state.rs
  kernel/src/cpu/percpu.rs
  kernel/src/cpu/vc.rs
  kernel/src/locking/rwlock.rs
  kernel/src/locking/spinlock.rs
  kernel/src/sev/ghcb.rs
  kernel/src/sev/msr_protocol.rs
  kernel/src/sev/utils.rs
  kernel/src/stage2.rs
Labels: ready-to-merge

#518 Add a rudimentary build system script
  Documentation/docs/installation/BUILD_RECIPES.md
  Documentation/docs/installation/INSTALL.md
  Documentation/mkdocs.yml
  build
  configs/all-targets.json
  configs/hyperv-target.json
  configs/qemu-target.json
  configs/vanadium-target.json
  scripts/build.py
Labels: in-review
