Repository coconut-svsm/svsm, pull requests merged in 2025-05, with the labels that each got.

#657 platform/tdp: Add IPI support
  kernel/src/cpu/msr.rs
  kernel/src/cpu/percpu.rs
  kernel/src/cpu/x86/apic.rs
  kernel/src/cpu/x86/x2apic.rs
  kernel/src/platform/tdp.rs
  kernel/src/tdx/apic.rs
  kernel/src/tdx/mod.rs
Labels: ready-to-merge

#671 Update to 1.84.1 for strict_provenance use in copy_bytes
  .github/workflows/rust.yml
  elf/src/load_segments.rs
  igvmbuilder/src/igvm_firmware.rs
  kernel/Cargo.toml
  kernel/src/cpu/ipi.rs
  kernel/src/debug/gdbstub.rs
  kernel/src/mm/alloc.rs
  kernel/src/mm/vm/mapping/api.rs
  kernel/src/utils/immut_after_init.rs
  rust-toolchain.toml
  user/init/Cargo.toml
  user/lib/src/lib.rs
Labels: wait-for-review, in-review

#678 request: create all request processing tasks from the primary loop
  kernel/src/cpu/ipi.rs
  kernel/src/cpu/percpu.rs
  kernel/src/cpu/smp.rs
  kernel/src/hyperv/hv.rs
  kernel/src/mm/virtualrange.rs
  kernel/src/platform/tdp.rs
  kernel/src/requests.rs
  kernel/src/svsm.rs
  kernel/src/task/mod.rs
  kernel/src/task/schedule.rs
  kernel/src/task/tasks.rs
Labels: in-review

#635 virtio-blk storage via mmio using virtio-drivers [v3]
  Cargo.lock
  Cargo.toml
  Makefile
  igvmmeasure/Cargo.toml
  kernel/Cargo.toml
  kernel/src/block/api.rs
  kernel/src/block/error.rs
  kernel/src/block/mod.rs
  kernel/src/block/virtio_blk.rs
  kernel/src/error.rs
  kernel/src/fw_cfg.rs
  kernel/src/lib.rs
  kernel/src/locking/spinlock.rs
  kernel/src/platform/mod.rs
  kernel/src/platform/native.rs
  kernel/src/platform/snp.rs
  kernel/src/platform/tdp.rs
  kernel/src/sev/ghcb.rs
  kernel/src/testing.rs
  kernel/src/virtio/devices.rs
  kernel/src/virtio/error.rs
  kernel/src/virtio/hal.rs
  kernel/src/virtio/mod.rs
  scripts/launch_guest.sh
  scripts/test-in-svsm.sh
  virtio-drivers/Cargo.toml
  virtio-drivers/LICENSE
  virtio-drivers/src/Cargo.toml
  virtio-drivers/src/device/blk.rs
  virtio-drivers/src/device/common.rs
  virtio-drivers/src/device/mod.rs
  virtio-drivers/src/hal.rs
  virtio-drivers/src/hal/fake.rs
  virtio-drivers/src/lib.rs
  virtio-drivers/src/queue.rs
  virtio-drivers/src/queue/owning.rs
  virtio-drivers/src/transport/fake.rs
  virtio-drivers/src/transport/mmio.rs
  virtio-drivers/src/transport/mod.rs
  virtio-drivers/src/volatile.rs
Labels: in-review

#675 scripts: Fix QEMU launcher nocc mode
  scripts/launch_guest.sh
Labels: ready-to-merge

#673 CI: Boot SVSM under Qemu in NOCC mode
  .github/workflows/qemu.yml
  scripts/launch_guest.sh
  scripts/test-qemu-nocc-boot.sh
Labels: ready-to-merge

#677 Use strict_provenance for copy_bytes
  kernel/src/mm/guestmem.rs
Labels: wait-for-review, in-review

#703 kernel: remove manual UUID implementation
  Cargo.lock
  bootlib/Cargo.toml
  bootlib/src/firmware.rs
  bootlib/src/lib.rs
  igvmbuilder/src/ovmf_firmware.rs
  kernel/src/platform/snp_fw.rs
  kernel/src/utils/fw_meta.rs
Labels: in-review

#709 Documentation: update the mailing list address
  Documentation/docs/developer/CONTRIBUTING.md
  Documentation/docs/index.md
  README.md
Labels: ready-to-merge
