Repository coconut-svsm/svsm, pull requests merged in 2025-08, with the labels that each got.

#679 Add verification for page frame allocator with safe permission-based memory access
  Cargo.lock
  Cargo.toml
  kernel/Cargo.toml
  kernel/src/address.rs
  kernel/src/address.verus.rs
  kernel/src/address_inner.verus.rs
  kernel/src/lib.rs
  kernel/src/mm/address_space.rs
  kernel/src/mm/address_space.verus.rs
  kernel/src/mm/address_space_spec.verus.rs
  kernel/src/mm/alloc.rs
  kernel/src/mm/alloc.verus.rs
  kernel/src/mm/alloc_free.verus.rs
  kernel/src/mm/alloc_info.verus.rs
  kernel/src/mm/alloc_inner.verus.rs
  kernel/src/mm/alloc_perms.verus.rs
  kernel/src/mm/alloc_types.verus.rs
  kernel/src/types.verus.rs
  kernel/src/utils/mod.rs
  kernel/src/utils/tcb_ptr.rs
  verify_external/src/hw_spec/mm.verus.rs
  verify_external/src/hw_spec/mod.rs
  verify_external/src/lib.rs
  verify_external/src/ptr.rs
  verify_external/src/ptr.verus.rs
  verify_proof/Cargo.toml
  verify_proof/src/bits.verus.rs
  verify_proof/src/frac_perm.rs
  verify_proof/src/frac_ptr.rs
  verify_proof/src/lib.rs
  verify_proof/src/nonlinear.rs
  verify_proof/src/set.rs
  verify_proof/src/sum.rs
  verus_macro_stub/src/lib.rs
Labels: in-review, release-feature

#768 mm: introduce `PerCPUMapping` for type-specific mappings
  bootlib/src/kernel_launch.rs
  cpuarch/src/vmsa.rs
  kernel/src/cpu/vmsa.rs
  kernel/src/mm/ptguards.rs
  kernel/src/platform/native.rs
  kernel/src/platform/tdp.rs
  kernel/src/protocols/core.rs
Labels: release-feature

#764 Remove unsafe custom checks
  .github/workflows/rust.yml
  Cargo.toml
  Makefile
  scripts/unsafe_blocks_report.sh
Labels: release-feature

#786 cpu/apic: Fix handle_icr_write
  kernel/src/cpu/apic.rs
Labels: wait-for-update, in-review
