Repository coconut-svsm/svsm, pull requests merged in 2025-07, with the labels that each got.

#733 unsafe blocks: add options to Makefile and new script to print stats
  Makefile
  scripts/unsafe_blocks_report.sh
Labels: wait-for-review, in-review

#752 virtio-drivers: Add missing SAFETY comments
  virtio-drivers/src/hal/fake.rs
  virtio-drivers/src/queue.rs
Labels: in-review

#747 Document unsafe blocks in memory management code
  kernel/src/debug/gdbstub.rs
  kernel/src/mm/alloc.rs
  kernel/src/mm/guestmem.rs
  kernel/src/mm/page_visibility.rs
  kernel/src/mm/pagebox.rs
  kernel/src/mm/pagetable.rs
  kernel/src/mm/ptguards.rs
  kernel/src/mm/validate.rs
  kernel/src/mm/vm/mapping/api.rs
Labels: in-review

#771 Fix `test_make_ro_after_init()`
  kernel/src/mm/ro_after_init.rs
Labels: release-blocker

#770 debug: fix safety issues with debugger implementation
  kernel/src/debug/gdbstub.rs
  kernel/src/debug/stacktrace.rs
Labels: release-feature
